### PR TITLE
Make the main Bible text larger for easier reading

### PR DESCRIPTION
**Pull request by noahsettersten**
Apologies. I had intended to create this within only my fork instead: https://github.com/noahsettersten/Reader/pull/1

### CODE REVIEW

**Comment by camilstaps** [comment]
No worries. It's a good idea; I have added it as an option in 7bbb275.

**Comment by noahsettersten** [comment]
Quick work there! Thanks for incorporating that idea. My Hebrew is beginner-level, and having the vowel pointing larger is helpful for my reading.

**Comment by noahsettersten** [comment]
Also, thank you for sharing this tool with the public. I've found it very helpful for my studies.

**Comment by camilstaps** [comment]
Glad to hear that! :)

**Pull request closed without merging**
